sudo: false
language: python
cache: pip
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - BASEDIR="https://raw.githubusercontent.com/open-contracting/standard-maintenance-scripts/master"
install:
  - curl -s -S $BASEDIR/tests/install.sh | bash -
  - pip install -e .[test]
  - pip install coveralls
script:
  - curl -s -S $BASEDIR/tests/script.sh | bash -
  - nosetests --with-coverage --cover-package=ocdskit
after_success:
  coveralls
